PromptClass: SimplePrompt
prompt_configs:
  few_shot: true
  few_shot_text: "question: get people name with age equal 25 table: id, name, age \n SELECT name FROM table WHERE age = 25"
  no_need_param: 20
  instruction_text: ""